import {
  Activity,
  ArrowUpRight,
  BadgeCheck,
  Blocks,
  BookOpen,
  Bot,
  CalendarClock,
  ChartNoAxesCombined,
  CircleAlert,
  CircleCheck,
  CircleDollarSign,
  CircleHelp,
  CirclePlay,
  ClipboardCheck,
  Compass,
  Copy,
  CornerLeftUp,
  CornerRightDown,
  Database,
  Download,
  FileBox,
  FlaskConical,
  FolderKanban,
  FolderOutput,
  GitBranch,
  GraduationCap,
  HeartPulse,
  House,
  Hammer,
  Landmark,
  Layers,
  Library,
  LibraryBig,
  Lightbulb,
  Link as LinkIcon,
  ListChecks,
  LucideIcon,
  MessagesSquare,
  Milestone,
  PanelTop,
  PanelsTopLeft,
  PackageOpen,
  Plug,
  Replace,
  Rows3,
  Scale,
  ScanSearch,
  Search,
  ShieldCheck,
  Sparkles,
  TableProperties,
  TriangleAlert,
  Upload,
  Zap,
  Workflow
} from "lucide-react";

const iconTokens: Record<string, LucideIcon> = {
  activity: Activity,
  "arrow-up-right": ArrowUpRight,
  "badge-check": BadgeCheck,
  blocks: Blocks,
  "book-open": BookOpen,
  bot: Bot,
  "calendar-clock": CalendarClock,
  "chart-no-axes-combined": ChartNoAxesCombined,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "circle-dollar-sign": CircleDollarSign,
  "circle-help": CircleHelp,
  "circle-play": CirclePlay,
  "clipboard-check": ClipboardCheck,
  compass: Compass,
  copy: Copy,
  "corner-left-up": CornerLeftUp,
  "corner-right-down": CornerRightDown,
  database: Database,
  download: Download,
  "file-box": FileBox,
  "flask-conical": FlaskConical,
  "folder-kanban": FolderKanban,
  "folder-output": FolderOutput,
  "git-branch": GitBranch,
  "graduation-cap": GraduationCap,
  "heart-pulse": HeartPulse,
  hammer: Hammer,
  house: House,
  landmark: Landmark,
  layers: Layers,
  library: Library,
  "library-big": LibraryBig,
  lightbulb: Lightbulb,
  link: LinkIcon,
  "list-checks": ListChecks,
  "messages-square": MessagesSquare,
  milestone: Milestone,
  "panel-top": PanelTop,
  "panels-top-left": PanelsTopLeft,
  "package-open": PackageOpen,
  plug: Plug,
  replace: Replace,
  "rows-3": Rows3,
  scale: Scale,
  "scan-search": ScanSearch,
  search: Search,
  "shield-check": ShieldCheck,
  "table-properties": TableProperties,
  "triangle-alert": TriangleAlert,
  upload: Upload,
  zap: Zap,
  workflow: Workflow
};

export function IconToken({
  token,
  className
}: {
  token?: string;
  className?: string;
}) {
  const Icon = token ? iconTokens[token] : undefined;

  return Icon ? (
    <Icon className={className} aria-hidden="true" />
  ) : (
    <Sparkles className={className} aria-hidden="true" />
  );
}
